version: "3.1"
services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_USER: gc
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: games
    ports:
      - 3307:3306
